13:16:54,72 root INFO column 'is_canceled' converted to bool type.
13:17:03,710 root INFO column 'arrival_date' converted to datetime.
13:17:07,615 root INFO column 'direct_booking' created.
13:17:07,791 root INFO column 'is_repeated_guest' converted to bool type.
13:18:13,658 root INFO column 'is_canceled' converted to bool type.
13:18:15,476 root INFO column 'arrival_date' converted to datetime.
13:18:16,314 root INFO column 'direct_booking' created.
13:18:16,394 root INFO column 'is_repeated_guest' converted to bool type.
13:20:13,412 root INFO column 'is_canceled' converted to bool type.
13:20:15,326 root INFO column 'arrival_date' converted to datetime.
13:20:16,194 root INFO column 'direct_booking' created.
13:20:16,264 root INFO column 'is_repeated_guest' converted to bool type.
13:23:14,708 root INFO column 'is_canceled' converted to bool type.
13:23:16,720 root INFO column 'arrival_date' converted to datetime.
13:23:17,698 root INFO column 'direct_booking' created.
13:23:17,782 root INFO column 'is_repeated_guest' converted to bool type.
11:33:13,801 root INFO column 'is_canceled' converted to bool type.
11:33:15,796 root INFO column 'arrival_date' converted to datetime.
11:33:16,717 root INFO column 'direct_booking' created.
11:33:16,791 root INFO column 'is_repeated_guest' converted to bool type.
11:34:13,792 root INFO column 'is_canceled' converted to bool type.
11:34:15,913 root INFO column 'arrival_date' converted to datetime.
11:34:16,849 root INFO column 'direct_booking' created.
11:34:16,927 root INFO column 'is_repeated_guest' converted to bool type.
11:37:57,622 root INFO column 'is_canceled' converted to bool type.
11:37:59,503 root INFO column 'arrival_date' converted to datetime.
11:38:00,405 root INFO column 'direct_booking' created.
11:38:00,473 root INFO column 'is_repeated_guest' converted to bool type.
11:42:03,714 root INFO column 'is_canceled' converted to bool type.
11:42:05,724 root INFO column 'arrival_date' converted to datetime.
11:42:06,702 root INFO column 'direct_booking' created.
11:42:06,795 root INFO column 'is_repeated_guest' converted to bool type.
11:42:47,229 root INFO column 'is_canceled' converted to bool type.
11:42:49,86 root INFO column 'arrival_date' converted to datetime.
11:42:50,4 root INFO column 'direct_booking' created.
11:42:50,83 root INFO column 'is_repeated_guest' converted to bool type.
11:47:12,767 root INFO column 'is_canceled' converted to bool type.
11:47:15,450 root INFO column 'arrival_date' converted to datetime.
11:47:16,222 root INFO column 'direct_booking' created.
11:47:16,301 root INFO column 'is_repeated_guest' converted to bool type.
11:55:35,58 root INFO column 'is_canceled' converted to bool type.
11:55:40,930 root INFO column 'arrival_date' converted to datetime.
11:55:42,679 root INFO column 'direct_booking' created.
11:55:42,905 root INFO column 'is_repeated_guest' converted to bool type.
11:59:56,441 root INFO column 'is_canceled' converted to bool type.
12:00:10,138 root INFO column 'is_canceled' converted to bool type.
12:00:12,545 root INFO column 'arrival_date' converted to datetime.
12:00:13,546 root INFO column 'direct_booking' created.
12:00:13,652 root INFO column 'is_repeated_guest' converted to bool type.
12:00:38,988 root INFO column 'is_canceled' converted to bool type.
12:00:42,424 root INFO column 'arrival_date' converted to datetime.
12:00:43,772 root INFO column 'direct_booking' created.
12:00:43,900 root INFO column 'is_repeated_guest' converted to bool type.
12:00:57,412 root INFO column 'is_canceled' converted to bool type.
12:01:11,387 root INFO column 'arrival_date' converted to datetime.
12:01:15,750 root INFO column 'direct_booking' created.
12:01:16,25 root INFO column 'is_repeated_guest' converted to bool type.
12:51:13,772 root INFO File loaded successfully.
12:51:13,970 root INFO column 'is_canceled' converted to bool type.
12:51:29,151 root INFO column 'arrival_date' converted to datetime.
12:51:34,30 root INFO column 'direct_booking' created.
12:51:34,329 root INFO column 'is_repeated_guest' converted to bool type.
12:54:08,87 root INFO File loaded successfully.
12:54:08,229 root INFO column 'is_canceled' converted to bool type.
12:54:22,409 root INFO column 'arrival_date' converted to datetime.
12:54:26,890 root INFO column 'direct_booking' created.
12:54:27,132 root INFO column 'is_repeated_guest' converted to bool type.
11:37:17,21 root INFO File loaded successfully.
11:37:40,232 root INFO File loaded successfully.
11:37:40,248 root INFO column 'is_canceled' converted to bool type.
11:37:41,986 root INFO column 'arrival_date' converted to datetime.
11:37:42,747 root INFO column 'direct_booking' created.
11:37:42,826 root INFO column 'is_repeated_guest' converted to bool type.
14:02:29,764 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 20, in get_top_agent_reservations_in_country
    df_results = sqlf.database_actions.query(q_query)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 39, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
14:02:55,59 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 77, in main
    sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 36, in get_reservations_and_guest_from_specific_year_within_range
    df_results = sqlf.database_actions.query(q_query)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 39, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
14:02:58,510 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    database_actions.query(q_query)
NameError: name 'database_actions' is not defined
name 'database_actions' is not defined
14:06:48,81 root INFO Ending Application!
14:08:09,27 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 20, in get_top_agent_reservations_in_country
    df_results = sqlf.database_actions.query(q_query)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 39, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
14:08:12,528 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    sqlf.database_actions.query(q_query)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "C:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 39, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
14:12:52,353 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 39, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
14:28:08,405 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect_copy.py", line 40, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
14:38:40,22 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 39, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
14:43:14,673 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 39, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
14:46:29,533 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'tbl'. (208) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect_copy.py", line 45, in ReadSqlQuery
    df = pd.read_sql_query(query, conn)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'tbl'. (208) (SQLExecDirectW)")
[SQL: SELECT * FROM tbl]
(Background on this error at: https://sqlalche.me/e/20/f405)
(pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'tbl'. (208) (SQLExecDirectW)")
[SQL: SELECT * FROM tbl]
(Background on this error at: https://sqlalche.me/e/20/f405)
14:47:51,698 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect_copy.py", line 45, in ReadSqlQuery
    df = pd.read_sql_query(sQuery, conn)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'SELECT g.children, AVG(r.stays_in_weekend_nights + r.stays_in_week_nights) AS average_nights\n    FROM Reservation r\n    JOIN Guest g\n    ON r.GuestId = g.GuestId\n    GROUP BY g.children;'
Not an executable object: 'SELECT g.children, AVG(r.stays_in_weekend_nights + r.stays_in_week_nights) AS average_nights\n    FROM Reservation r\n    JOIN Guest g\n    ON r.GuestId = g.GuestId\n    GROUP BY g.children;'
14:49:16,27 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 81, in main
    sq.get_impact_of_number_children_on_nights_stayed()
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 49, in get_impact_of_number_children_on_nights_stayed
    sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect_copy.py", line 45, in ReadSqlQuery
    df = pd.read_sql_query(sQuery, conn)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'SELECT g.children, AVG(r.stays_in_weekend_nights + r.stays_in_week_nights) AS average_nights\nFROM Reservation r\nJOIN Guest g\nON r.GuestId = g.GuestId\nGROUP BY g.children;'
Not an executable object: 'SELECT g.children, AVG(r.stays_in_weekend_nights + r.stays_in_week_nights) AS average_nights\nFROM Reservation r\nJOIN Guest g\nON r.GuestId = g.GuestId\nGROUP BY g.children;'
14:49:50,707 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 77, in main
    sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 36, in get_reservations_and_guest_from_specific_year_within_range
    df_results = sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect_copy.py", line 45, in ReadSqlQuery
    df = pd.read_sql_query(sQuery, conn)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'SELECT *\n    FROM Reservation r\n    JOIN Guest g\n    ON g.GuestId = r.GuestId\n    WHERE YEAR(reservation_status_date) = 2016 and adr BETWEEN 100 AND 200 and is_canceled != 0;'
Not an executable object: 'SELECT *\n    FROM Reservation r\n    JOIN Guest g\n    ON g.GuestId = r.GuestId\n    WHERE YEAR(reservation_status_date) = 2016 and adr BETWEEN 100 AND 200 and is_canceled != 0;'
14:50:07,915 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 20, in get_top_agent_reservations_in_country
    df_results = sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect_copy.py", line 45, in ReadSqlQuery
    df = pd.read_sql_query(sQuery, conn)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: "SELECT TOP 10 r.* , g.*\n    FROM Reservation r\n    JOIN Guest g\n    ON r.GuestId = g.GuestId\n    JOIN (SELECT TOP 1 r.agent, COUNT(r.agent) AS num_bookings\n        FROM Reservation r\n        JOIN Guest g\n        ON r.GuestId = g.GuestId\n        WHERE g.country = 'PRT' and r.agent != 'no agent'\n        GROUP BY r.agent\n        ORDER BY num_bookings DESC) top_agent\n    ON top_agent.agent = r.agent\n    WHERE r.agent = top_agent.agent and r.guestId = g.GuestId;"
Not an executable object: "SELECT TOP 10 r.* , g.*\n    FROM Reservation r\n    JOIN Guest g\n    ON r.GuestId = g.GuestId\n    JOIN (SELECT TOP 1 r.agent, COUNT(r.agent) AS num_bookings\n        FROM Reservation r\n        JOIN Guest g\n        ON r.GuestId = g.GuestId\n        WHERE g.country = 'PRT' and r.agent != 'no agent'\n        GROUP BY r.agent\n        ORDER BY num_bookings DESC) top_agent\n    ON top_agent.agent = r.agent\n    WHERE r.agent = top_agent.agent and r.guestId = g.GuestId;"
14:51:40,587 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 77, in main
    sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 38, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 38, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 10, in __init__
    self.e_hotel_name = HotelType[reservation_row['hotel'].upper().replace(' ', '_')]
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
14:51:55,733 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in get_top_agent_reservations_in_country
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 10, in __init__
    self.e_hotel_name = HotelType[reservation_row['hotel'].upper().replace(' ', '_')]
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
14:54:07,645 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in get_top_agent_reservations_in_country
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 10, in __init__
    self.e_hotel_name = HotelType[reservation_row['hotel'].upper().replace(' ', '_')].name
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
15:04:23,667 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 77, in main
    sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 38, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 38, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 10, in __init__
    self.e_hotel_name = HotelType[reservation_row['hotel'].upper().replace(' ', '_')].name
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
15:07:21,786 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in get_top_agent_reservations_in_country
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 10, in __init__
    self.e_hotel_name = HotelType[reservation_row['hotel'].upper().replace(' ', '_')]
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
15:07:34,318 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in get_top_agent_reservations_in_country
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 10, in __init__
    self.e_hotel_name = HotelType[reservation_row['hotel'].upper().replace(' ', '_')]
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
15:09:50,226 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in get_top_agent_reservations_in_country
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 11, in __init__
    self.b_reservation_is_canceled = reservation_row['is_canceled']
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
15:18:57,507 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 77, in main
    sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 39, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 39, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 11, in __init__
    self.e_hotel_name = HotelType[reservation_row['hotel'].upper().replace(' ', '_')]
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
15:19:57,844 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    sq.get_top_agent_reservations_in_country(country)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in get_top_agent_reservations_in_country
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 22, in <listcomp>
    ls_reservations = [Reservation(row) for row, index in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 11, in __init__
    self.e_hotel_name = HotelType[reservation_row['hotel'].upper().replace(' ', '_')]
TypeError: 'int' object is not subscriptable
'int' object is not subscriptable
15:29:34,449 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 77, in main
    sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
NameError: name 'row' is not defined
name 'row' is not defined
15:35:12,819 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 70, in main
    a = sq.get_top_agent_reservations_in_country(country)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 20, in get_top_agent_reservations_in_country
    df_results = sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 39, in ReadSqlQuery
    df = pd.read_sql_query(sQuery,self.m_engine)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'OptionEngine' object has no attribute 'execute'
'OptionEngine' object has no attribute 'execute'
15:47:47,486 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 72, in main
    print (*each)
TypeError: print() argument after * must be an iterable, not Reservation
print() argument after * must be an iterable, not Reservation
15:48:24,988 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 72, in main
    print ('*' + each)
TypeError: can only concatenate str (not "Reservation") to str
can only concatenate str (not "Reservation") to str
16:04:15,902 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 80, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal']]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Undefined'
'Undefined'
16:07:21,492 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 80, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal']]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Undefined'
'Undefined'
16:09:02,981 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 80, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal']]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Undefined'
'Undefined'
16:09:21,784 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 80, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal']]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Undefined'
'Undefined'
16:09:45,718 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 80, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 40, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal']]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Undefined'
'Undefined'
11:31:26,787 root INFO Ending Application!
22:38:58,685 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 99, in main
    if ls_top_agent_reservations.empty:
AttributeError: 'list' object has no attribute 'empty'
'list' object has no attribute 'empty'
22:40:23,562 root ERROR Country not found.
22:40:46,783 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'fsf'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'sf'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'sfs'. (207)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 114, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 56, in get_reservations_and_guest_from_specific_year_within_range
    df_results = sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 47, in ReadSqlQuery
    df = pd.read_sql_query(query, conn)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'fsf'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'sf'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'sfs'. (207)")
[SQL: SELECT *
    FROM Reservation r
    JOIN Guest g
    ON g.GuestId = r.GuestId
    WHERE YEAR(reservation_status_date) = fsf and adr BETWEEN sf AND sfs and is_canceled != 0;]
(Background on this error at: https://sqlalche.me/e/20/f405)
(pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'fsf'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'sf'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'sfs'. (207)")
[SQL: SELECT *
    FROM Reservation r
    JOIN Guest g
    ON g.GuestId = r.GuestId
    WHERE YEAR(reservation_status_date) = fsf and adr BETWEEN sf AND sfs and is_canceled != 0;]
(Background on this error at: https://sqlalche.me/e/20/f405)
22:41:48,937 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 114, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 58, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 58, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal']]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Undefined'
'Undefined'
22:42:10,853 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 114, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 58, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 58, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal']]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Undefined'
'Undefined'
22:42:29,660 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 114, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 58, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 58, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal']]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'Undefined'
'Undefined'
22:44:34,952 root ERROR Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'er'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'r'. (207)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 114, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 56, in get_reservations_and_guest_from_specific_year_within_range
    df_results = sqlf.database_actions.query(q_query)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_actions.py", line 24, in query
    df_result = db.ReadSqlQuery(sql)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\database_connect.py", line 47, in ReadSqlQuery
    df = pd.read_sql_query(query, conn)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 397, in read_sql_query
    return pandas_sql.read_query(
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "C:\Users\Owner\anaconda3\lib\site-packages\pandas\io\sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Owner\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'er'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'r'. (207)")
[SQL: SELECT *
    FROM Reservation r
    JOIN Guest g
    ON g.GuestId = r.GuestId
    WHERE YEAR(reservation_status_date) = 2106 and adr BETWEEN er AND r and is_canceled != 0;]
(Background on this error at: https://sqlalche.me/e/20/f405)
(pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'er'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'r'. (207)")
[SQL: SELECT *
    FROM Reservation r
    JOIN Guest g
    ON g.GuestId = r.GuestId
    WHERE YEAR(reservation_status_date) = 2106 and adr BETWEEN er AND r and is_canceled != 0;]
(Background on this error at: https://sqlalche.me/e/20/f405)
22:44:47,176 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 114, in main
    ls_within_range_reservations = sq.get_reservations_and_guest_from_specific_year_within_range(year, min, max)
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 58, in get_reservations_and_guest_from_specific_year_within_range
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\sqlf\queries.py", line 58, in <listcomp>
    ls_reservations = [Reservation(row) for index, row in df_results.iterrows()]
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\entities\reservation.py", line 17, in __init__
    self.e_meal = MealType[reservation_row['meal'].upper()]
  File "C:\Users\Owner\anaconda3\lib\enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'UNDEFINED'
'UNDEFINED'
23:14:28,882 root ERROR Invalid menu choice.
23:33:58,529 root ERROR Country not found.
23:34:54,178 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 101, in main
    elif country in countries.keys:
TypeError: argument of type 'builtin_function_or_method' is not iterable
argument of type 'builtin_function_or_method' is not iterable
21:55:24,578 root INFO File loaded successfully.
21:55:24,578 root INFO column 'is_canceled' converted to bool type.
21:55:26,308 root INFO column 'arrival_date' converted to datetime.
21:55:27,105 root INFO column 'direct_booking' created.
21:55:27,182 root INFO column 'is_repeated_guest' converted to bool type.
21:58:31,177 root INFO File loaded successfully.
21:58:31,195 root INFO column 'is_canceled' converted to bool type.
21:58:32,968 root INFO column 'arrival_date' converted to datetime.
21:58:33,758 root INFO column 'direct_booking' created.
21:58:33,823 root INFO column 'is_repeated_guest' converted to bool type.
21:59:13,713 root ERROR Country not found.
21:59:21,483 root ERROR Invalid menu choice.
21:59:32,547 root ERROR Invalid menu choice.
22:00:54,363 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 101, in main
    country = countries.get(country).title()
AttributeError: 'NoneType' object has no attribute 'title'
'NoneType' object has no attribute 'title'
22:01:47,661 root ERROR Invalid menu choice.
22:02:15,302 root ERROR Input not valid.
22:02:53,261 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 122, in main
    if len(year) == 4 and year > 2014 and year < 2018 and float(min) and float(max):
TypeError: '>' not supported between instances of 'str' and 'int'
'>' not supported between instances of 'str' and 'int'
22:03:09,469 root ERROR Traceback (most recent call last):
  File "c:\Users\Owner\Documents\Course\Mid Year Project\Hotel Reservations\src\main.py", line 122, in main
    if len(year) == 4 and year > 2014 and year < 2018 and float(min) and float(max):
TypeError: '>' not supported between instances of 'str' and 'int'
'>' not supported between instances of 'str' and 'int'
22:04:25,718 root ERROR Input not valid.
